version: '3.3'

services: 
  elixir:
    container_name: 'elixir-sandbox'
    build:
      context: .
      dockerfile: ./docker/elixir/Dockerfile
    env_file: .env
    tty: true
    stdin_open: true
    ports:
      - '4000:14000'
    volumes:
      - ./src:/app
